### ISSUE TITLE
Valid VIN code error

### ISSUE THREAD

**Issue by cyberz** [thephilip/vindec#5]
Wrong validation for valid VIN codes. Example: WBA3B5G5XDNS01478

**Comment by thephilip** [comment]
I'm sorry that I am only just seeing this.  I'll try to look into this this week.  Of course, you are welcome to submit a PR too.

**Comment by thephilip** [comment]
Confirmed.  The VIN 'WBA3B5G5XDNS01478' reports back as false.  Need to figure out if the issue is in vindec or vindec-validator.

**Comment by thephilip** [comment]
I have confirmed the issue is actually an error on the part of [vindec-validator](https://github.com/thephilip/vindec-validator/issues/3).

**Comment by thephilip** [comment]
Fixed: [PR](https://github.com/thephilip/vindec-validator/pull/4).
